<?php
return [
    'hero_slides' => [
        'title' => 'Hero / Slides',
        'table' => 'hero_slides',
        'upload_dir' => 'slides',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'title' => ['label' => 'Título', 'type' => 'text', 'required' => true],
            'subtitle' => ['label' => 'Subtítulo', 'type' => 'textarea'],
            'cta_label' => ['label' => 'Texto do CTA', 'type' => 'text'],
            'cta_url' => ['label' => 'URL do CTA', 'type' => 'text'],
            'image_path' => ['label' => 'Imagem', 'type' => 'image'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
    'services' => [
        'title' => 'Serviços',
        'table' => 'services',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'name' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'summary' => ['label' => 'Resumo', 'type' => 'textarea'],
            'details' => ['label' => 'Detalhes', 'type' => 'textarea'],
            'icon' => ['label' => 'Ícone / Emoji', 'type' => 'text'],
            'slug' => ['label' => 'Slug', 'type' => 'text'],
            'featured' => ['label' => 'Destaque', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
    'products' => [
        'title' => 'Produtos',
        'table' => 'products',
        'upload_dir' => 'products',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'name' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'category' => ['label' => 'Categoria', 'type' => 'select', 'options' => ['Novo' => 'Novo', 'Seminovo' => 'Seminovo', 'Acessório' => 'Acessório']],
            'summary' => ['label' => 'Resumo', 'type' => 'textarea'],
            'price_label' => ['label' => 'Preço / Rótulo', 'type' => 'text'],
            'condition_label' => ['label' => 'Condição', 'type' => 'text'],
            'cta_label' => ['label' => 'Texto do CTA', 'type' => 'text'],
            'cta_url' => ['label' => 'URL do CTA', 'type' => 'text'],
            'image_path' => ['label' => 'Imagem', 'type' => 'image'],
            'featured' => ['label' => 'Destaque', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
    'promotions' => [
        'title' => 'Promoções',
        'table' => 'promotions',
        'upload_dir' => 'promotions',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'title' => ['label' => 'Título', 'type' => 'text', 'required' => true],
            'summary' => ['label' => 'Resumo', 'type' => 'textarea'],
            'price_label' => ['label' => 'Preço / Rótulo', 'type' => 'text'],
            'old_price_label' => ['label' => 'Preço anterior', 'type' => 'text'],
            'badge' => ['label' => 'Selo', 'type' => 'text'],
            'valid_until' => ['label' => 'Validade', 'type' => 'date'],
            'cta_label' => ['label' => 'Texto do CTA', 'type' => 'text'],
            'cta_url' => ['label' => 'URL do CTA', 'type' => 'text'],
            'image_path' => ['label' => 'Imagem', 'type' => 'image'],
            'featured' => ['label' => 'Destaque', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
    'testimonials' => [
        'title' => 'Depoimentos',
        'table' => 'testimonials',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'author_name' => ['label' => 'Nome', 'type' => 'text', 'required' => true],
            'content' => ['label' => 'Depoimento', 'type' => 'textarea'],
            'rating' => ['label' => 'Nota', 'type' => 'number'],
            'source_label' => ['label' => 'Origem', 'type' => 'text'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
    'about_blocks' => [
        'title' => 'Sobre / About Blocks',
        'table' => 'about_blocks',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'title' => ['label' => 'Título', 'type' => 'text', 'required' => true],
            'content' => ['label' => 'Conteúdo', 'type' => 'textarea'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
    'branches' => [
        'title' => 'Unidades',
        'table' => 'branches',
        'default_order' => 'sort_order ASC, id DESC',
        'fields' => [
            'name' => ['label' => 'Nome da unidade', 'type' => 'text', 'required' => true],
            'address' => ['label' => 'Endereço', 'type' => 'textarea'],
            'business_hours' => ['label' => 'Horário', 'type' => 'text'],
            'map_embed' => ['label' => 'Mapa (iframe)', 'type' => 'textarea'],
            'phone' => ['label' => 'Telefone', 'type' => 'text'],
            'whatsapp_number' => ['label' => 'WhatsApp', 'type' => 'text'],
            'sort_order' => ['label' => 'Ordem', 'type' => 'number'],
            'is_active' => ['label' => 'Ativo', 'type' => 'checkbox'],
        ],
    ],
];
